[tool.djlint]
blank_line_after_tag = "load,extends,include,endblock"
close_void_tags = true
format_attribute_template_tags = true
ignore = "H014,H015,H006"
indent = 2
line_break_after_multiline_tag = true
max_attribute_length = 0
max_blank_lines = 0
max_line_length = 100
preserve_blank_lines = true
profile = "django"
use_gitignore = true

[tool.ruff]
exclude = [
    ".direnv",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "build",
    "dist",
    "env.py",
    "manage.py",
    "media",
    "migrations",
    "node_modules",
    "site-packages",
    "static",
    "templates",
    "venv",
    "__pycache__",
    "wsgi.py",
    "asgi.py",
]
line-length = 79
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
ignore = [
    "Q000",
    "Q001",
    "Q003",
    "F401",
]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "DJ",
    "Q",
    "I",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"settings.py" = [
    "F401",
    "F403",
    "F405",
]
"tests.py" = ["F401"]

[tool.ruff.format]
quote-style = "single"
